---
test:
  workers:
    type: local
    number: 1
  rounds:
    - label: change Car Owner.
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: caliper/fabcar/changeCarOwner.js
        arguments:
          assets: 1000


   



